import Head from 'next/head';
import { MdSentimentDissatisfied } from 'react-icons/md';
import { Button } from '../Buttons';
import { useRouter } from 'next/router';

export default function ErrorScreen({
  message = 'Something went wrong',
  returnUrl = '/',
  returnUrlMessage = 'Back to Home',
}) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative mx-auto flex min-h-screen w-full items-center justify-center p-6 2xl:container">
        <div className="flex flex-col items-center justify-center gap-4 text-center">
          <MdSentimentDissatisfied size={120} className="text-gray-400" />
          <p className="border-t border-gray-300 pt-4 text-xl">{message}</p>
          {/* <div></div> */}
          <Button onClick={() => router.push(returnUrl)} small>
            {returnUrlMessage}
          </Button>
        </div>
      </div>
    </>
  );
}
