// import { GridLoader } from 'react-spinners';
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from 'tailwind.config';
import Head from 'next/head';
import dynamic from 'next/dynamic';
const GridLoader = dynamic(
  () =>
    import('react-spinners').then((module) => ({ default: module.GridLoader })),
  {
    ssr: false,
  }
);

export default function FullPageLoader({ message }) {
  const { theme } = resolveConfig(tailwindConfig);
  return (
    <>
      <Head>
        <title>Loading...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative mx-auto flex min-h-screen w-full items-center justify-center p-6 2xl:container">
        <div className="flex flex-col gap-2 text-center">
          <div>
            <GridLoader color={theme.colors.primary[500]} />
          </div>
          <p>{message}</p>
        </div>
      </div>
    </>
  );
}
