import Head from 'next/head';
import { MainLayout } from '@/components/Layouts';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import { useState } from 'react';
import { CourseSchedulerTable } from '@/components/Tables';
import { SearchForm } from '@/components/Forms';
import { courses } from '@/lib/test_data/scheduler';

export default function Schedules() {
  const tabs = ['college', 'SHS'];
  const [activeTab, setActiveTab] = useState(tabs[0]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Scheduler | CMI - Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col gap-6 p-6">
        <div className="flex items-center justify-between gap-4 rounded-md bg-gray-50 p-3">
          <p>Select a course, year, and section for scheduling</p>
          <div className="w-full max-w-[350px]">
            <SearchForm placeholder={`Search ${activeTab} courses`} />
          </div>
        </div>
        <Tabs
          className="flex flex-col gap-4"
          onSelect={(index) => setActiveTab(tabs[index])}
        >
          <TabList className="scrollbar-hide flex w-full gap-2 overflow-x-auto">
            <Tab selectedClassName="tab-active" className="tab">
              College
            </Tab>
            <Tab selectedClassName="tab-active" className="tab">
              Senior High
            </Tab>
          </TabList>

          <TabPanel>
            <CourseSchedulerTable type="college" />
          </TabPanel>
          <TabPanel>
            <CourseSchedulerTable type="shs" />
          </TabPanel>
        </Tabs>
      </div>
    </>
  );
}

Schedules.getLayout = function getLayout(page) {
  return <MainLayout name="Scheduler">{page}</MainLayout>;
};
