import Head from 'next/head';
import { MainLayout } from '@/components/Layouts';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import { collegeCourses } from '@/lib/test_data/courses';
import { CourseTable, LevelTable, KinderTable } from '@/components/Tables';

export default function Courses() {
  return (
    <>
      <Head>
        <title>Courses | CMI - Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col gap-6 p-6">
        <Tabs className="flex flex-col">
          <TabList className="scrollbar-hide mb-4 flex w-full gap-2 overflow-x-auto border-b border-gray-300 pb-4">
            <Tab selectedClassName="tab-active" className="tab">
              Kinder
            </Tab>
            <Tab selectedClassName="tab-active" className="tab">
              Elementary
            </Tab>
            <Tab selectedClassName="tab-active" className="tab">
              Junior High
            </Tab>
            <Tab selectedClassName="tab-active" className="tab">
              Senior High
            </Tab>
            <Tab selectedClassName="tab-active" className="tab">
              College
            </Tab>
          </TabList>
          <TabPanel>
            <KinderTable />
          </TabPanel>
          <TabPanel>
            <LevelTable type="elementary" />
          </TabPanel>
          <TabPanel>
            <LevelTable type="jhs" />
          </TabPanel>
          <TabPanel>
            <CourseTable type="shs" />
          </TabPanel>
          <TabPanel>
            <CourseTable data={collegeCourses} type="college" />
          </TabPanel>
        </Tabs>
      </div>
    </>
  );
}

Courses.getLayout = function getLayout(page) {
  return <MainLayout name="Courses & Levels">{page}</MainLayout>;
};
