import Head from 'next/head';
import { MainLayout } from '@/components/Layouts';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import { collegeCourses } from '@/lib/test_data/courses';
import { CourseTable } from '@/components/Tables';

export default function Courses() {
  return (
    <>
      <Head>
        <title>Courses | CMI - Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col gap-6 p-6">
        <Tabs className="flex flex-col">
          <TabList className="scrollbar-hide mb-4 flex w-full gap-2 overflow-x-auto">
            <Tab selectedClassName="tab-active" className="tab">
              College
            </Tab>
            <Tab selectedClassName="tab-active" className="tab">
              Senior High
            </Tab>
          </TabList>

          <TabPanel>
            <CourseTable data={collegeCourses} type="college" />
          </TabPanel>
          <TabPanel>
            <CourseTable type="shs" />
          </TabPanel>
        </Tabs>
      </div>
    </>
  );
}

Courses.getLayout = function getLayout(page) {
  return <MainLayout name="Courses">{page}</MainLayout>;
};
